### PR TITLE
fix(scripts): add support for parsing version argument with v0.0.0

### LINKED ISSUE #21: [Task] Operator-sdk install script should support v0.0.0-type argument
Argument to installs script should support argument such as `v1.22.2` and allows specifying target directory.

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #21 

Support `v0.0.0` type argument and target directory to install binary to.

### CODE REVIEW

**Comment by tthvo** [comment]
Since all variables are single-use as arguments, there is no need to export them as env var. This also avoids conflicts since those env var stays during shell session).

**Comment by maxcao13** [comment]
It's v1.22.1 not v1.22.2?

**Comment by tthvo** [comment]
oh sorry have not updated the default value yet since 1.22.1. Will do that!

**Review by maxcao13 — APPROVED** [review]
Looks good thanks.

**Pull request merged**
