### PR TITLE
fix(scripts): fix install_operator_sdk.sh checks on error status code

### LINKED ISSUE #1: [Task] Failure in script to install operator-sdks should log errors
When a failure occurs (i.e. operator-sdk version is not available), the script `Done.` at the end instead of `[ERROR] ...`

This line could be the issue as the next if block check for exit code.

https://github.com/tthvo/operator-knowledge-hub/blob/e2cae0da890fbf3a7598b6e930e0f1abacc3deda/scripts/install_operator_sdk#L19

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #1 

Fixes install_operator_sdk checking wrong error status code (i.e. cd command).
Rename scripts with `.sh` extensions.

### CODE REVIEW

**Comment by maxcao13** [comment]
This is for the new operator-sdk version 1.22.1 which will be correct to use for cryostat-operator when your upgrade PR is merged right?

**Review by maxcao13 — CHANGES_REQUESTED** [review]
Also I think maybe the names should be delimited with "-" and not "_" because it seems a lot of other scripts follow that convention. e.g. in cryostat (repeated-integration-tests.bash, build-images.sh, etc.)

**Comment by maxcao13** [comment]
Oh, I didn't know the requested changes button looks so scary. :0

**Comment by tthvo** [comment]
> This is for the new operator-sdk version 1.22.1 which will be correct to use for cryostat-operator when your upgrade PR is merged right?

Yeh yeh this script is used for fetching operator-sdk binaries :D So it would be able to be used in any scenarios

**Comment by tthvo** [comment]
> Oh, I didn't know the requested changes button looks so scary. :0

Haha yeh bloody red lol :D i will add ur suggestions in^^

**Review by maxcao13 — APPROVED** [review]
Looks great thanks.

**Pull request merged**
